import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseSessionInitializer } from "@/contexts/SupabaseSessionInitializer";
import NextTopLoader from "nextjs-toploader";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin", "greek"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} antialiased`}>
				<NextTopLoader
					color="#FF8904"
					initialPosition={0.04}
					crawlSpeed={300}
					height={2}
					crawl={true}
					easing="ease"
					speed={350}
					shadow="0 0 10px #FF8904,0 0 5px #FF8904"
					zIndex={9999}
				/>
				<CartProvider>
					<SupabaseSessionInitializer>{children}</SupabaseSessionInitializer>
				</CartProvider>
				<Toaster richColors />
			</body>
		</html>
	);
}
