import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";
import { Footer } from "@/components/Footer";
import { WhatsAppButton } from "@/components/WhatsAppButton";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseSessionInitializer } from "@/contexts/SupabaseSessionInitializer";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin", "greek"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} antialiased`}>
				<CartProvider>{children}</CartProvider>
				<SupabaseSessionInitializer />
				<WhatsAppButton />
				<Footer />
				<Toaster />
			</body>
		</html>
	);
}
